---
- name: install httpd
  hosts: webservers
  become: true
  tasks:
  - name: install apache httpd 
    apt:
      name: apache2
      state: present
  - name: install latest version of httpd
    yum:
      name: httpd
      state: latest       






- hosts: all
  become: yes
  tasks:
    - name: Install Apache on CentOS and Ubuntu
      package:
        name: "{{ apache_pkg }}"
        state: present
      vars:
        apache_pkg: "{{ 'httpd' if ansible_distribution == 'CentOS' else 'apache2' }}"